export const staticUsers = [
  {
    id: 1,
    email: "admin@uninfo.com",
    password: "admin123",
    role: "Admin",
    name: "Admin User",
    loginFailures: 0,
    lockedUntil: 0,
    createdAt: new Date().toISOString(),
    emailVerified: true,
    verificationToken: null,
    verificationExpires: null,
  },
  {
    id: 2,
    email: "student@uninfo.com",
    password: "student123",
    role: "Student",
    name: "Test Student",
    loginFailures: 0,
    lockedUntil: 0,
    createdAt: new Date().toISOString(),
    emailVerified: true,
    verificationToken: null,
    verificationExpires: null,
  },
];
